services:
  supervisor:
    image: "ghcr.io/mlibrary/sidekiq-supervisor-unstable:latest"
    ports:
     - "3333:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MARIADB_USER=supervisor
      - MARIADB_PASSWORD=supervisor_password
      - MARIADB_DATABASE=supervisor
      - MARIADB_ROOT_PASSWORD=pass
      - DATABASE_HOST=database


  database:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_USER=supervisor
      - MARIADB_PASSWORD=supervisor_password
      - MARIADB_DATABASE=supervisor
      - MARIADB_ROOT_PASSWORD=pass

  sftp:
    image: 'atmoz/sftp'
    volumes:
      - ./sftp/search_daily_bibs:/home/alma/search_daily_bibs
      - ./sftp/ssh/ssh_client_rsa_key.pub:/home/alma/.ssh/keys/id_rsa.pub:ro
      - ./sftp/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftp/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: alma:1001

  support:
    build: 
      context: support_dbs/.
      target: development 
    volumes:
      - ./support_dbs/.:/app
      - support_gem_cache:/gems
    environment:
      - HATHIFILES_MYSQL_CONNECTION=mysql2://root:pass@hathifiles/hathifiles
      - HT_HOST=https://www.hathitrust.org
      - REDIS_URL=redis://redis:6379

  web:
    build:
      context: umich_catalog_indexing/.
      target: development
    depends_on:
      - 'redis'
    ports:
      - 9394:9394
    volumes:
      - ./umich_catalog_indexing/.:/app
      - ./sftp/ssh/ssh_client_rsa_key:/etc/secret-volume/id_rsa:ro
      - gem_cache:/gems
    environment:
      - REDIS_URL=redis://redis:6379
      - HLB_XML_ENDPOINT=https://apps.lib.umich.edu/browse/categories/xml.php 
      - NODB=1
    env_file:
      - ./umich_catalog_indexing/.env
      - ./umich_catalog_indexing/env.development
      - ./mock-ht/env.development

  redis:
    image: 'redis:6.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  solr:
    build: biblio/.
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo:2181
    depends_on:
      - zoo
    command: solr-foreground

  zoo:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  mock-ht:
    build: mock-ht/.
    ports:
      - 4444:4444
    volumes:
      - ./mock-ht/.:/app
    env_file:
      - ./mock-ht/env.development

  #hathifiles:
    #image: mariadb
    #volumes:
      #- hathidb:/var/lib/mysql
    #environment:
      #- MARIADB_ROOT_PASSWORD=pass
      #- MARIADB_USER=user
      #- MARIADB_PASSWORD=password
      #- MARIADB_DATABASE=hathifiles

  #hathioverlap:
    #image: mariadb
    #volumes:
      #- overlap:/var/lib/mysql
    #environment:
      #- MARIADB_ROOT_PASSWORD=pass
      #- MARIADB_USER=user
      #- MARIADB_PASSWORD=password
      #- MARIADB_DATABASE=overlap

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

volumes:
  gem_cache:
  support_gem_cache:
  redis:
  db_data:
  hathidb:
  overlap:
