version: '3.8'

services:
  sidekiq:
    build: sidekiq/.
    depends_on:
      - 'redis'
    ports:
     - "9292:9292"
    volumes:
      - ./sidekiq/.:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - SESSION_KEY=session_key
    command: bundle exec rackup -o 0.0.0.0

  sftp:
    image: 'atmoz/sftp'
    volumes:
      - ./sftp/search_daily_bibs:/home/alma/search_daily_bibs
      - ./sftp/ssh/ssh_client_rsa_key.pub:/home/alma/.ssh/keys/id_rsa.pub:ro
      - ./sftp/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftp/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: alma:1001

  support:
    build: 
      context: support_dbs/.
      target: development 
    volumes:
      - ./support_dbs/.:/app
      - support_gem_cache:/gems
    environment:
      - HATHIFILES_MYSQL_CONNECTION=mysql2://root:pass@hathifiles/hathifiles
      - HT_HOST=https://www.hathitrust.org

  web:
    build: umich_catalog_indexing/.
    depends_on:
      - 'redis'
    ports:
      - 9394:9394
    volumes:
      - ./umich_catalog_indexing/.:/app
      - ./sftp/ssh/ssh_client_rsa_key:/etc/secret-volume/id_rsa:ro
      - gem_cache:/gems
    environment:
      - SOLR_URL=http://solr:8026/solr/biblio
      - REDIS_URL=redis://redis:6379
      - HLB_XML_ENDPOINT=https://apps.lib.umich.edu/browse/categories/xml.php 
        #- JRUBY_OPTS=--debug
      - NODB=1
    env_file:
      - ./umich_catalog_indexing/.env
      - ./umich_catalog_indexing/.env-dev-values
      - ./mock-ht/.env-dev-values

  redis:
    image: 'redis:6.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  solr:
    build: biblio/.
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo:2181
    depends_on:
      - zoo
    command: solr-foreground

  zoo:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  mock-ht:
    build: mock-ht/.
    ports:
      - 4444:4444
    volumes:
      - ./mock-ht/.:/app
    env_file:
      - ./mock-ht/.env-dev-values


  hathidb:
    image: mariadb
    volumes:
      - hathidb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=hathifiles

  hathioverlap:
    image: mariadb
    volumes:
      - overlap:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=overlap

  #prometheus:
    #image: prom/prometheus
    #ports:
      #- 9090:9090
    #volumes:
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  gem_cache:
  support_gem_cache:
  redis:
  hathidb:
  overlap:
