version: '3'

services:
  monitor:
    build: monitor/.
    ports: 
      - "3000:3000"
    volumes:
      - ./monitor/.:/app
      - monitor_gem_cache:/gems
    env_file:
      - ./monitor/.env
      - ./monitor/.env-dev-values

  monitor-db:
    image: mariadb
    volumes:
      - monitor_db_data:/var/lib/mysql
    env_file:
      - ./monitor/.env-dev-values

  sidekiq:
    build: sidekiq/.
    ports:
     - "9292:9292"
    volumes:
      - ./sidekiq/.:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - SESSION_KEY=session_key
    command: bundle exec rackup -o 0.0.0.0

  sftp:
    image: 'atmoz/sftp'
    volumes:
      - ./sftp/search_daily_bibs:/home/alma/search_daily_bibs
      - ./sftp/ssh/ssh_client_rsa_key.pub:/home/alma/.ssh/keys/id_rsa.pub:ro
      - ./sftp/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftp/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: alma:1001

  web:
    build: umich_catalog_indexing/.
    ports:
      - 9394:9394
    volumes:
      - ./umich_catalog_indexing/.:/app
      - ./sftp/ssh/ssh_client_rsa_key:/etc/secret-volume/id_rsa:ro
      - gem_cache:/gems
    environment:
      - SOLR_URL=http://solr:8026/solr/biblio
      - REDIS_URL=redis://redis:6379
      - HLB_XML_ENDPOINT=https://apps.lib.umich.edu/browse/categories/xml.php 
        #- JRUBY_OPTS=--debug
      - NODB=1
    env_file:
      - ./umich_catalog_indexing/.env
      - ./umich_catalog_indexing/.env-dev-values
      - ./mock-ht/.env-dev-values

  redis:
    image: 'redis:6.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  solr:
    build: biblio/.
    ports:
     - "8026:8026"
  
  #mock-ht:
    #build: mock-ht/.
    #ports:
      #- 4444:4444
    #volumes:
      #- ./mock-ht/.:/app
    #env_file:
      #- ./mock-ht/.env-dev-values

  #hathidb:
    #image: ghcr.io/hathitrust/hathifiles-dev-db:latest

  #hathioverlap:
    #build: overlap/.

  #prometheus:
    #image: prom/prometheus
    #ports:
      #- 9090:9090
    #volumes:
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml

#networks:
  #default:
    #external:
      #name: example

volumes:
  gem_cache:
  redis:
  monitor_db_data:
  monitor_gem_cache:
