scrape_configs:
- job_name: pushgateway
  honor_labels: true
  honor_timestamps: true
  static_configs:
    - targets: ['pushgateway:9091']
- job_name: catalog_indexer
  static_configs:
    - targets: ['web:9394']
