name: Build solr image
on:
  workflow_dispatch:
    inputs:
      tag-to-be-created:
        description: tag
        required: true
      commit-sha:
        description: github commit hash
        required: true
jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.commit-sha }}
    - name: Check that tag doesn't already exist
      id: tag_check
      env:
        TAG: ${{ github.event.inputs.tag-to-be-created }}
      run: |
        echo "checking if tag exists: $TAG"
        if git rev-parse "refs/tags/$TAG" &> /dev/null; then
          echo "tag: $TAG already exists; delete it before continuing"
          false
        else
          echo "tag doesn't exist yet. will continue to creating tag"
        fi
    - name: Tag commit
      env: 
        TAG: ${{ github.event.inputs.tag-to-be-created }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git tag $TAG
        git push origin $TAG

  build-production:
    needs: tag-commit
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: "search-solr"
      tag: ${{ github.event.inputs.tag-to-be-created }}
      dockerfile: "biblio/Dockerfile.prod"
      docker_context: "biblio/."
    secrets: inherit
