name: Build latest catalog-solr-unstable and catalog-indexer-unstable on push to main

on: 
  push:
    branches: [ main ]

jobs:
  build-catalog-solr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push catalog-solr
      env:
        IMAGE_NAME: catalog-solr-unstable
      uses: docker/build-push-action@v2
      with:
        context: biblio/.
        push: true
        tags: |
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
           
  build-catalog-indexer-unstable:
    name: Build unstable ${{ github.event.inputs.tag }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.INDEXER_IMAGE_NAME }}
      tag: ${{ github.sha }}
      dockerfile: umich_catalog_indexing/Dockerfile
      docker_context: umich_catalog_indexing/.
    secrets: inherit

