name: Build latest catalog-solr-unstable and catalog-indexer-unstable on push

on: push

jobs:
  build-catalog-solr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push catalog-solr
      env:
        IMAGE_NAME: catalog-solr-unstable
      uses: docker/build-push-action@v2
      with:
        context: biblio/.
        push: true
        tags: |
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
           
  build-catalog-indexer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push catalog-indexer
      env:
        IMAGE_NAME: catalog-indexer-unstable
      uses: docker/build-push-action@v2
      with:
        context: umich_catalog_indexing/.
        push: true
        tags: |
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
