name: Build Support Image

on:
  workflow_dispatch:
    inputs:
      tag-to-be-created:
        description: tag
        required: true
      commit-sha:
        description: github commit hash
        required: true

env:
  TAG_PREFIX: "support"

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
        ref: ${{ github.event.inputs.commit-sha }}
    - name: Check that tag doesn't already exist
      id: tag_check
      env:
        TAG: ${{ env.TAG_PREFIX }}-${{ github.event.inputs.tag-to-be-created }}
      run: |
        echo "checking if tag exists: $TAG"
        if git rev-parse "refs/tags/$TAG" &> /dev/null; then
          echo "tag: $TAG already exists; delete it before continuing"
          false
        else
          echo "tag doesn't exist yet. will continue to creating tag"
        fi
    - name: Tag commit
      env: 
        TAG: support-${{ github.event.inputs.tag-to-be-created }}
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git tag $TAG
        git push origin $TAG

  build-production:
    needs: tag-commit
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: "catalog-support"
      tag: support-${{ github.event.inputs.tag-to-be-created }}
      dockerfile: "support_dbs/Dockerfile"
      docker_context: "support_dbs/."
    secrets: inherit
