name: Build latest catalog-solr and traject on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    #- name: Build and Push catalog-solr
      #env:
        #IMAGE_NAME: catalog-solr-unstable
      #uses: docker/build-push-action@v2
      #with:
        #context: biblio/.
        #push: true
        #tags: |
           #ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           #ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
    #- name: Setup upterm session
      #uses: lhotari/action-upterm@v1
      #with:
        ### limits ssh access and adds the ssh public key for the user which triggered the workflow
        #limit-access-to-actor: true
        ### limits ssh access and adds the ssh public keys of the listed GitHub users
        #limit-access-to-users: niquerio
    - name: Build and Push catalog-indexer
      env:
        IMAGE_NAME: catalog-indexer-unstable
      uses: docker/build-push-action@v2
      with:
        context: umich_catalog_indexing/.
        push: true
        tags: |
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
