name: Deploy Catalog Reindexer

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

env:
  IMAGE: ghcr.io/mlibrary/catalog-indexer

jobs:
  deploy-deployment:
    name: "Deploy ${{ github.event.inputs.tag }} to reindexer"
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy Catalog-Indexer to Reindexer
      uses: mlibrary/deploy-to-kubernetes@v2
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ env.IMAGE }}:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}
        deployment: catalog-reindexer
        container: catalog-reindexer
