#saved so that I can have a workflow to try out in a branch
name: Manual Build image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'image to build'
        required: true
        type: choice
        options:
          - api
      tag:
        description: tag
        required: true

jobs:
  get-image-info:
    runs-on: ubuntu-latest
    outputs:
      directory: ${{ steps.get_step.outputs.directory }}
      image_name: ${{ steps.get_step.outputs.image_name }}
    steps:
    - name: Get step
      id: get_step
      env:
        IMAGE: ${{ github.event.inputs.image }}
      run: |
        if [[ $IMAGE == "api" ]]; then
            echo "directory=api" >> "$GITHUB_OUTPUT"
            echo "image_name=search.catalog-api" >> "$GITHUB_OUTPUT"
        else
          echo "somehow didn't provide a image"
          false
        fi

  build-unstable:
    name: Build unstable ${{ github.event.inputs.tag }}
    needs: [get-image-info]
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ needs.get-image-info.outputs.image_name }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: "${{ needs.get-image-info.outputs.directory }}/Dockerfile"
      docker_context: "${{ needs.get-image-info.outputs.directory }}/."
    secrets: inherit
