name: Production Start Reindex

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
      shards: 
         description: Number of shards (default 1)
         default: "1"
         required: true

jobs:
  build-production:
    name: Build production ${{ github.event.inputs.tag }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.INDEXER_IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: umich_catalog_indexing/Dockerfile
      docker_context: umich_catalog_indexing/.
    secrets: inherit
      
  deploy-configset:
    needs: build-production #needed because of tag validation
    name: Zip and send configset
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.tag }}
    - name: zip configset
      env:
        TAG: ${{ github.event.inputs.tag }}
      run: | 
        cd biblio/conf
        echo -n $TAG > version.txt
        zip -r ../biblio.zip .
    - name: send configset to production and create new collection
      env: 
        USER: ${{ vars.SOLR_USER }}
        PASSWORD: ${{ secrets.SOLR_PASSWORD }}
        HOST: ${{ vars.SOLR_HOST }}
        SHARDS: ${{ github.event.inputs.shards }}
      run:  |
        DATE=`date +%Y%m%d` 
        BIBLIO="biblio_$DATE"
        cd biblio
        echo "Sending configset"
        # -f causes non 0 return if not response 200
        curl -f -u $USER:$PASSWORD -X PUT --header "Content-Type: applicatgion/octet-stream" --data-binary @biblio.zip "$HOST/api/cluster/configs/$BIBLIO" || exit 
        echo "Creating $BIBLIO collection with this configset"
        curl -f -u $USER:$PASSWORD "$HOST/solr/admin/collections?action=CREATE&name=$BIBLIO&numShards=$SHARDS&collection.configName=$BIBLIO" || exit 
        echo "Pointing reindex alias to $BIBLIO collection"
        curl -f -u $USER:$PASSWORD "$HOST/solr/admin/collections?action=CREATEALIAS&name=biblio-reindex&collections=$BIBLIO" || exit 

  deploy-reindexer:
    needs: build-production
    name: Deploy to production
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.INDEXER_IMAGE_NAME }}:${{ github.event.inputs.tag }}
      file: environments/catalog-indexer/production/reindexer-image.txt
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    secrets: inherit

  
