name: Build Release

on:
  release:
    types: [ released ]

jobs:
  build-production:
    name: Build production ${{ github.event.release.tag_name }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.INDEXER_IMAGE_NAME }}
      tag: ${{ github.event.release.tag_name }}
      dockerfile: umich_catalog_indexing/Dockerfile
      docker_context: umich_catalog_indexing/.
    secrets: inherit


  #deploy-production:
    #needs: build-production
    #name: Deploy ${{ github.event.inputs.kind }} to production
    #uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    #with:
      #image: ghcr.io/mlibrary/${{ vars.INDEXER_IMAGE_NAME }}:${{ github.event.inputs.tag }}
      #file: environments/catalog-indexer/production/reindexer-image.txt
      #CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
      #CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      #CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    #secrets: inherit
